import { clerkMiddleware, createRouteMatcher } from '@clerk/nextjs/server';
import { NextResponse } from 'next/server';

const ADMIN_SLUG = process.env.NEXT_PUBLIC_ADMIN_ROUTE_SLUG || 'admin';
const STAFF_SLUG = process.env.NEXT_PUBLIC_STAFF_ROUTE_SLUG || 'staff-portal';

export default clerkMiddleware(async (auth, req) => {
  const url = req.nextUrl;
  const pathname = url.pathname;

  // Clean request headers to prevent header spoofing from outside
  const requestHeaders = new Headers(req.headers);
  const isClientClaimedInternal = req.headers.get('x-tgc-internal-admin');
  
  // Create base response and set baseline security headers
  const response = NextResponse.next();
  response.headers.set('X-Frame-Options', 'DENY');
  response.headers.set('X-Content-Type-Options', 'nosniff');
  response.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');

  // Bypass Clerk session validation for custom auth API endpoints
  if (pathname.startsWith('/api/auth/')) {
    return response;
  }

  // 1. If someone visits public /admin directly while obfuscated slug is active, block with 404
  if (ADMIN_SLUG !== 'admin' && (pathname === '/admin' || pathname.startsWith('/admin/'))) {
    // Only trust internal rewrites generated by Next.js server itself
    return NextResponse.rewrite(new URL('/not-found', req.url));
  }

  // 2. Secret Admin Slug Rewrite: Map /${ADMIN_SLUG}/* internally to /admin/*
  if (ADMIN_SLUG !== 'admin' && (pathname === `/${ADMIN_SLUG}` || pathname.startsWith(`/${ADMIN_SLUG}/`))) {
    const subPath = pathname.replace(new RegExp(`^/${ADMIN_SLUG}`), '');
    const targetUrl = new URL(`/admin${subPath || ''}`, req.url);
    targetUrl.search = url.search;
    
    requestHeaders.set('x-tgc-internal-admin', 'true');

    return NextResponse.rewrite(targetUrl, {
      request: {
        headers: requestHeaders,
      },
    });
  }

  // 3. Secret Staff Portal Rewrite: Map /${STAFF_SLUG}/* internally to /admin/products/*
  if (pathname === `/${STAFF_SLUG}` || pathname.startsWith(`/${STAFF_SLUG}/`)) {
    const subPath = pathname.replace(new RegExp(`^/${STAFF_SLUG}`), '');
    const targetUrl = new URL(`/admin/products${subPath || ''}`, req.url);
    targetUrl.search = url.search;
    
    requestHeaders.set('x-tgc-internal-admin', 'true');

    return NextResponse.rewrite(targetUrl, {
      request: {
        headers: requestHeaders,
      },
    });
  }

  return response;
});

export const config = {
  matcher: [
    // Skip Next.js internals and all static files, unless found in search params
    '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
    // Always run for API routes
    '/(api|trpc)(.*)',
  ],
};

